streamline:
  outputs:
    dev:
      dataset: streamline_stg
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: streamline_prod
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev